// Auto-generated by scripts/generate-last-updated.mjs from the latest git
// commit date, right before `dev`/`build` runs. Do not edit by hand; the
// value here is only what happened to be committed last.
export const LAST_UPDATED = "Sep 2026";
